### ISSUE TITLE
klipper

### ISSUE THREAD

**Issue by BamsyTheSergal** [Masong19hippows/gspca-kinect2#1]
how would i go about making this work with klipper?

**Comment by Masong19hippows** [comment]
I'm honestly not sure what the best way is because I don't have a 3d printer to test with that runs the klipper firmware. What model of 3d printer are you using and what's your setup? I think maybe the best way would be to use a pi or something as a camera setup with this driver and use the video color output as an input to some ip camera server like motion https://github.com/motioneye-project/motioneye

I don't know the best way without knowing more info though

**Comment by BamsyTheSergal** [comment]
i am using a cheap mini pc, debian klipper install with kiauh and crowsnest, with a skr mini e3 v2 upgrade board, ender 3 (first version), i seem to have detected the kinect is infact connected, but nothing video comes out of it no matter what version of this kinect2 software i used, it said the script ran but refused to actually start the camera, i also think i remember seeing something about certificates but idk honestly.

**Comment by Masong19hippows** [comment]
Out of scope of this project
